<?php
/**
 * BarcodesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BarcodeService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Barcode Shared Service
 *
 * Barcode Shared Service API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BarcodeService;

use \BarcodeService\Configuration;
use \BarcodeService\ApiException;
use \BarcodeService\ObjectSerializer;

/**
 * BarcodesApiTest Class Doc Comment
 *
 * @category Class
 * @package  BarcodeService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BarcodesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createBarcode
     *
     * Create an unique barcode.
     *
     */
    public function testCreateBarcode()
    {
    }

    /**
     * Test case for showBarcode
     *
     * Show the barcode for a code.
     *
     */
    public function testShowBarcode()
    {
    }
}
