<?php
/**
 * ShowBarcodeResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BarcodeService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Barcode Shared Service
 *
 * Barcode Shared Service API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BarcodeService;

/**
 * ShowBarcodeResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ShowBarcodeResponse
 * @package     BarcodeService
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShowBarcodeResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShowBarcodeResponse"
     */
    public function testShowBarcodeResponse()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "base64"
     */
    public function testPropertyBase64()
    {
    }
}
