<?php
/**
 * ShowBarcodeResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BarcodeService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Barcode Shared Service
 *
 * Barcode Shared Service API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BarcodeService\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShowBarcodeResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ShowBarcodeResponse
 * @package     BarcodeService
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShowBarcodeResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShowBarcodeResponse"
     */
    public function testShowBarcodeResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "base64"
     */
    public function testPropertyBase64()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
